import { CreditCard, RefreshCw, Users, UserPlus, XCircle } from 'lucide-react';

export const ACCOUNT_TABS = [
  {
    id: 'payment-method',
    label: 'Payment Method',
    icon: CreditCard,
  },
  {
    id: 'update-payment',
    label: 'Update Payment',
    icon: RefreshCw,
  },
  {
    id: 'manage-users',
    label: 'Manage Users',
    icon: Users,
  },
  {
    id: 'add-user',
    label: 'Add User',
    icon: UserPlus,
  },
  {
    id: 'close-account',
    label: 'Close Account',
    icon: XCircle,
  },
];

export const ALL_PERMISSIONS = [
  { label: 'Campaigns', key: 'campaignsEnabled' },
  { label: 'Campaigns (Read Only)', key: 'campaignsReadOnly' },
  { label: 'Contacts', key: 'contactsEnabled' },
  { label: 'Workflows', key: 'workflowsEnabled' },
  { label: 'Workflows (Read Only)', key: 'workflowsReadOnly' },
  { label: 'Triggers', key: 'triggersEnabled' },
  { label: 'Funnels', key: 'funnelsEnabled' },
  { label: 'Websites', key: 'websitesEnabled' },
  { label: 'Opportunities', key: 'opportunitiesEnabled' },
  { label: 'Dashboard Stats', key: 'dashboardStatsEnabled' },
  { label: 'Bulk Requests', key: 'bulkRequestsEnabled' },
  { label: 'Appointments', key: 'appointmentsEnabled' },
  { label: 'Reviews', key: 'reviewsEnabled' },
  { label: 'Online Listings', key: 'onlineListingsEnabled' },
  { label: 'Phone Calls', key: 'phoneCallEnabled' },
  { label: 'Conversations', key: 'conversationsEnabled' },
  { label: 'Assigned Data Only', key: 'assignedDataOnly' },
  { label: 'AdWords Reporting', key: 'adwordsReportingEnabled' },
  { label: 'Membership', key: 'membershipEnabled' },
  { label: 'Facebook Ads Reporting', key: 'facebookAdsReportingEnabled' },
  { label: 'Attribution Report', key: 'attributionReportEnabled' },
  { label: 'Agent Reporting', key: 'agentReportingEnabled' },
  { label: 'Bot Service', key: 'botService' },
  { label: 'Social Planner', key: 'socialPlanner' },
  { label: 'Blogging', key: 'bloggingEnabled' },
  { label: 'Invoices', key: 'invoiceEnabled' },
  { label: 'Affiliate Manager', key: 'affiliateManagerEnabled' },
  { label: 'Content AI', key: 'contentAiEnabled' },
  { label: 'Refunds', key: 'refundsEnabled' },
  { label: 'Record Payment', key: 'recordPaymentEnabled' },
  { label: 'Cancel Subscription', key: 'cancelSubscriptionEnabled' },
  { label: 'Payments', key: 'paymentsEnabled' },
  { label: 'Communities', key: 'communitiesEnabled' },
  { label: 'Export Payments', key: 'exportPaymentsEnabled' },
];

export const DEFAULT_PERMISSIONS = {
  campaignsEnabled: true,
  campaignsReadOnly: false,
  contactsEnabled: true,
  workflowsEnabled: true,
  workflowsReadOnly: false,
  triggersEnabled: true,
  funnelsEnabled: true,
  websitesEnabled: true,
  opportunitiesEnabled: true,
  dashboardStatsEnabled: true,
  bulkRequestsEnabled: false,
  appointmentsEnabled: true,
  reviewsEnabled: true,
  onlineListingsEnabled: true,
  phoneCallEnabled: true,
  conversationsEnabled: true,
  assignedDataOnly: false,
  adwordsReportingEnabled: false,
  membershipEnabled: false,
  facebookAdsReportingEnabled: false,
  attributionReportEnabled: false,
  agentReportingEnabled: false,
  botService: false,
  socialPlanner: false,
  bloggingEnabled: false,
  invoiceEnabled: false,
  affiliateManagerEnabled: false,
  contentAiEnabled: false,
  refundsEnabled: false,
  recordPaymentEnabled: false,
  cancelSubscriptionEnabled: false,
  paymentsEnabled: false,
  communitiesEnabled: false,
  exportPaymentsEnabled: false,
};

export const COMPANY_ID = process.env.REACT_APP_GHL_COMPANY_ID || 'company_id_from_env';
